# Generated by Django 4.2.13 on 2024-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Guardian', models.CharField(max_length=100)),
                ('CertificateType', models.CharField(max_length=20)),
                ('CadetRank', models.CharField(max_length=20)),
                ('PassingYear', models.IntegerField()),
                ('Grade', models.CharField(max_length=10)),
                ('Unit', models.CharField(max_length=50)),
                ('Directorate', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
    ]
