# Generated by Django 4.2.13 on 2024-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_name', models.CharField(max_length=255)),
                ('date_month_year', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Guardian', models.CharField(max_length=100)),
                ('CertificateType', models.CharField(max_length=20)),
                ('CadetRank', models.CharField(max_length=20)),
                ('PassingYear', models.IntegerField()),
                ('Grade', models.CharField(max_length=10)),
                ('Unit', models.CharField(max_length=50)),
                ('Directorate', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('final_certificate', models.ImageField(blank=True, null=True, upload_to='media/certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('cbse_no', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('fathers_name', models.CharField(max_length=255)),
                ('school_college', models.CharField(max_length=255)),
                ('year_of_passing_b_certificate', models.CharField(max_length=255)),
                ('attach_photo_b_certificate', models.ImageField(blank=True, null=True, upload_to='media')),
                ('fresh_or_failure', models.CharField(max_length=255)),
                ('attendance_1st_year', models.IntegerField()),
                ('attendance_2nd_year', models.IntegerField()),
                ('attendance_3rd_year', models.IntegerField()),
                ('attendance_total', models.IntegerField()),
                ('home_address', models.TextField()),
                ('pass_fail', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('marks_subject1', models.IntegerField(blank=True, null=True)),
                ('marks_subject2', models.IntegerField(blank=True, null=True)),
                ('marks_subject3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
