# Generated by Django 4.2.13 on 2024-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
