# Generated by Django 4.2.13 on 2024-07-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='CertificateType',
            field=models.CharField(blank=True, choices=[('A_Army', 'A Army'), ('A_AirForce', 'A AirForce'), ('A_Navy', 'A Navy'), ('B_AirForce', 'B AirForce'), ('B_Army', 'B Army'), ('B_Navy', 'B Navy'), ('C_Army', 'C Army')], max_length=20, null=True),
        ),
    ]
