# Generated by Django 4.2.13 on 2024-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='Directorate',
            field=models.CharField(blank=True, default='UP DIRECTORATE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Institute',
            field=models.CharField(blank=True, default='IIT Kanpur', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Place',
            field=models.CharField(blank=True, default='Kanpur', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Unit',
            field=models.CharField(blank=True, default='2UP CTR', max_length=50, null=True),
        ),
    ]
