# Generated by Django 4.2.13 on 2024-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
