# Generated by Django 4.2.13 on 2024-06-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_certificate_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='final_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='media/certificates/'),
        ),
    ]
