# Generated by Django 4.2.13 on 2024-07-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_certificate_is_rejected_certificate_is_reviewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='certificate',
            name='ceo_review_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='register_head_review_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reviewer_ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reviewer_register_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_head_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='reviewer_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='staff_review_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
