# Generated by Django 4.2.13 on 2024-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_certificate_directorate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='Directorate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
