# Generated by Django 4.2.13 on 2024-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_certificate_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ceo_signature_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='register_head_signature_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='staff_signature_applied',
            field=models.BooleanField(default=False),
        ),
    ]
