# Generated by Django 4.2.13 on 2024-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_certificate_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
