# Generated by Django 5.0.6 on 2024-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_certificate_final_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_name', models.CharField(max_length=255)),
                ('date_month_year', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('cbse_no', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('fathers_name', models.CharField(max_length=255)),
                ('school_college', models.CharField(max_length=255)),
                ('year_of_passing_b_certificate', models.CharField(max_length=255)),
                ('attach_photo_b_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('fresh_or_failure', models.CharField(max_length=255)),
                ('attendance_1st_year', models.IntegerField()),
                ('attendance_2nd_year', models.IntegerField()),
                ('attendance_3rd_year', models.IntegerField()),
                ('attendance_total', models.IntegerField()),
                ('home_address', models.TextField()),
                ('camp_details', models.ManyToManyField(related_name='student_details', to='mainapp.campdetail')),
            ],
        ),
    ]
